- name: Create sa.yml
  copy:
    dest: /tmp/sa.yml
    content: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: svcs-acct

- name: Apply sa.yml
  shell: kubectl create -f /tmp/sa.yml

- name: Generate kubeconfig file
  shell: kubectl config view --flatten --minify > /tmp/cluster-cert.txt

- name: Store kubeconfig file into ./config
  fetch:
    src: /tmp/cluster-cert.txt
    dest: ./config
    flat: yes