- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - { role: dependencies, tags: ["install_dependencies_role"] }

- hosts: master
  become: yes
  roles:
    - { role: cluster, tags: ["create_cluster_role"] }

- hosts: workers
  become: yes
  roles:
    - { role: configure, tags: ["configure_cluster_role"] }
